import { StyleSheet } from 'react-native';
import { colors, fonts, fontSize, spacing, radius } from './theme';

export const globalStyles = StyleSheet.create({
  pageContainer: {
    flex: 1,
    padding: spacing.xl,
    backgroundColor: colors.parchmentDark,
  },
  container: {
    flex: 1,
    padding: spacing.xl,
    backgroundColor: colors.parchment,
    borderColor: colors.ink,
    borderWidth: 1,
    borderRadius: radius.sm,
  },
  centeredContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.xl,
    backgroundColor: colors.parchmentDark,
  },
  card: {
    backgroundColor: colors.parchment,
    borderColor: colors.ink,
    borderWidth: 1,
    borderRadius: radius.sm,
    padding: spacing.lg,
  },
  topCard: {
    backgroundColor: colors.parchment,
    padding: spacing.lg,
    margin: spacing.lg,
    borderColor: colors.gold,
    borderWidth: 1,
    borderRadius: radius.sm,
    gap: spacing.sm,
  },
  button: {
    backgroundColor: colors.leather,
    borderColor: colors.gold,
    borderWidth: 1,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: radius.md,
    alignItems: 'center',
  },
  buttonText: {
    color: colors.gold,
    fontFamily: fonts.heading,
    fontWeight: '600',
    fontSize: fontSize.base,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  input: {
    borderWidth: 1,
    borderColor: colors.inkMuted,
    backgroundColor: colors.parchment,
    color: colors.ink,
    fontFamily: fonts.body,
    padding: spacing.md,
    borderRadius: radius.md,
    fontSize: fontSize.base,
  },
  title: {
    fontFamily: fonts.heading,
    fontSize: fontSize.xl,
    fontWeight: '700',
    color: colors.ink,
    marginBottom: spacing.lg,
    letterSpacing: 1,
  },
  titleCenter: {
    fontFamily: fonts.heading,
    fontSize: fontSize.xl,
    fontWeight: '700',
    color: colors.ink,
    marginBottom: spacing.lg,
    textAlign: 'center',
    letterSpacing: 1,
  },
  subtitle: {
    fontFamily: fonts.heading,
    fontSize: fontSize.md,
    fontWeight: '600',
    color: colors.inkSoft,
  },
  label: {
    fontFamily: fonts.body,
    fontWeight: '600',
    color: colors.ink,
  },
});
